[General]
; Allow the games to run without VBF archives at all
; If set to true, whole archives have to be unpacked.
allowNoVBF = false

[Logging]
; Change this value, if you want the loader to print all files that are accessed
; by the game.
logAccess=false

; Simply add new paths here. Each causes additional IO, so try not to have too
; many of them. Key name doesn't matter. Both absolute and relative paths are
; supported. Relative paths start in game's main directory. Paths higher on the
; list have priority.
[Paths]
mods=data/mods

