; FF10 module loader configuration file. Only ANSI and UTF16 encoding supported!
; Unless specified otherwise, all relative paths start in game's main directory

[general]
; If set to true, [modules] section contains a list of specific modules to load
; rather than a list of directories
disableAutoLoad=false

; A list of paths to autoload modules from. If no entry is specified or the
; config file is missing, defaults to single path "modules".
; If disableAutoLoad is set to true, it has to contain list of complete module
; paths rather than directories
[modules]
default=modules

[log]
; Do not allocate console nor send anything to stdout
disableConsole=true
; Disable creating and writing to a file log
disableFile=false
; Set log file path
logFile=hook.log
